### ISSUE TITLE
Browser net::ERR_CERT_AUTHORITY_INVALID, cert is for example.org

### ISSUE THREAD

**Issue by iva2k** [perki/backloop.dev#3]
Very much needed and very promising package!

I tried to add it to SvelteKit (vite.config.ts), and it got loaded, server started, backloop.dev reported that certs created (I see local files inside package's certs dir), however, pointing a chrome to the sub-domain does not work. Chrome reports net::ERR_CERT_AUTHORITY_INVALID, blocks access (no way to accept it), and clicking on the error reveals that cert is for:

```
Subject: example.org

Issuer: example.org

Expires on: Sep 2, 2024

Current date: Aug 3, 2024

PEM encoded chain:
-----BEGIN CERTIFICATE-----
...
```

**Comment by iva2k** [comment]
I'm trying to compare the cert shown by the browser to the ones saved locally, or the ones I can see in the debugger attached to vite.config.ts, and they don't match. I wonder where do the certs come from? I've used this code:

```ts
// vite.config.ts
import backloopHttpsOptions from 'backloop.dev';
...
export default defineConfig(async ({ mode }) => {
...
  const config: UserConfig = {
     server: {
          port: 4443,
          host: 'app.backloop.dev',
          https: backloopHttpsOptions
        }
  };
  return config;
});
```

**Comment by iva2k** [comment]
ok, I solved it - the server settings from `backloopHttpsOptions` were overridden by remnants of `@vitejs/plugin-basic-ssl` which I overlooked in `vite.config.ts`. Now with `@vitejs/plugin-basic-ssl` fully removed, https server works as expected.

**Comment by perki** [comment]
Hello !
Good that you solved it.
We could add a check and warn an non-compatibility message if plugin-basic-ssl is installed.

**Comment by iva2k** [comment]
> We could add a check and warn an non-compatibility message if plugin-basic-ssl is installed.
It could be helpful in this situation, however, since in my case it was my own oversight, not sure how many people encounter the same problem. Perhaps this issue itself is enough for them to read, or a note in installation doc.
