### ISSUE TITLE
Not working using Vite 6.0.3

### ISSUE THREAD

**Issue by TonyStark** [perki/backloop.dev#7]
Vite Config:
```
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import backloop from "vite-plugin-backloop.dev";

// https://vite.dev/config/
export default defineConfig({
  plugins: [react(), backloop("edutrack")],
  resolve: {
    alias: {
      "@": "/src", // maps @ to the src directory
    },
  },
});
```
Run Dev:
```
backloop.dev certificate OK, expires in 87 days
{ hostname: 'edutrack' }

  VITE v6.0.3  ready in 351 ms

  ➜  Network: https://edutrack.backloop.dev:5173/
  ➜  press h + enter to show help
```
Output in Browser:
```
Unable to connect

An error occurred during a connection to edutrack.backloop.dev:5173. 
```

**Comment by perki** [comment]
Hello @TonyStark 

Do you use v1.0.4 of vite-plugin-backloop.dev ? 

Regards, 
Pierre-Mikael

**Comment by perki** [comment]
In the last month, the certificate was revoked at least twice. I suspect that some bots are revoking certificates when they find their private keys available publicly on the internet. 
I decided to split the private key into two pieces, but this is not compatible with previous versions of bakloop.dev.

**Comment by TonyStark** [comment]
Hi @perki 
Yes it is v1.0.4
Regarding certificate revoked, i think its not working ssl on *.backloop.dev but if i try https://localhost:5173 instead then ssl is working.

**Comment by perki** [comment]
Hi @TonyStark this is surprising. 
It looks like your DNS is not resolving edutrack.backloop.dev to 127.0.0.1 (localhost) 

If you're on linux / osx you can add the following line to `/etc/hosts` file   
```
127.0.0.1 edutrack.backloop.dev
```
or add `edutrack.backloop.dev` to existing localhost line 
```
127.0.0.1	localhost edutrack.backloop.dev
```

**Comment by TonyStark** [comment]
Okay
Now getting this 
```
Secure Connection Failed

An error occurred during a connection to edutrack.backloop.dev:5173. Peer’s Certificate has been revoked.

Error code: SEC_ERROR_REVOKED_CERTIFICATE
```

**Comment by perki** [comment]
@TonyStark Thank you for the feedback
